version: '3'
services:
  censor_anything_frontend:
    image: max94/censor_anything_frontend:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/certs
    networks:
      - mynetwork

  censor_anything_backend:
    image: max94/censor_anything_backend:latest
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork: