# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG NODE_VERSION=18.16.0

FROM node:${NODE_VERSION}-alpine

# Use production node environment by default.
ENV NODE_ENV production


WORKDIR /usr/src/app

# Install Python, make, g++, pkgconf, and other dependencies from the main repository
RUN apk add --update python3 make g++ pkgconf cairo-dev jpeg-dev pango-dev giflib-dev

# Install pixman-dev from the edge/testing repository
RUN apk add --update --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing pixman-dev

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
# into this layer.
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

# Copy the rest of the source files into the image.
COPY . .

# Create the generated_images directory and change ownership to the node user
RUN mkdir -p ./generated_images && chown -R node:node ./generated_images

# Change ownership of the uploads directory to the node user
RUN chown -R node:node ./uploads

# Run the application as a non-root user.
USER node

# Expose the port that the application listens on.
EXPOSE 3000

# Run the application.
CMD npm start
