name: Frontend Docker to GCP VM

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_docker_build_and_publish.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v1
    #- name: Login to DockerHub
    #  uses: docker/login-action@v1 
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}
    #- name: Build and push
    #  uses: docker/build-push-action@v2
    #  with:
    #    context: ./app
    #    file: ./app/Dockerfile
   #     push: true
    #    tags: max94/censor_anything_frontend:latest
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Start GCP VM and run Docker container
      run: |
        gcloud compute instances start censor-everything-big-vm --zone=us-central1-a
        gcloud compute ssh censor-everything-big-vm --zone=us-central1-a --command="\
          sudo curl -L \"https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose && \
          sudo chmod +x /usr/local/bin/docker-compose && \
          docker-compose up -d"
